# Generated by Django 4.1.3 on 2023-01-30 19:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=3)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('inspection_schedule', models.CharField(choices=[('EARLY WEEK', 'Mondays & Tuesdays.'), ('MIDWEEK', 'Wednesdays & Thursdays.'), ('WEEKEND', 'Fridays, Saturdays $ Sundays.')], max_length=50)),
                ('prefered_time', models.CharField(choices=[('MORNING', '7AM - 12PM.'), ('EVENING', '12PM - 6PM.')], max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
